geometry:
    pitch                           : 0.265                                #Pitch [m]
    alpha                           : 0.01                                  #Geometric parameter used for hull-calculations
    algorithm                       : "from_pointcloud"
    ptcloud_profile                 : "00_Ressources/outcloud.txt"   #Name of the pointcloud-file
    ptcloud_profile_unit            : "mm"                                  #m vs mm
    x_inlet                         : 0.0                                  #Shift Inlet along x [m]
    x_outlet                        : 0.28                                  #Shift Outlet along x [m]
    shift_domain                    : 0                                 #Shift Domain to have probes inside domain [m]

mesh:
    factor                          : 1                                   #Mesh-density factor
    ogrid_factor                    : 1                                     #o-grid-node-ratio
    delta_i                         : 0.0015                                #node-distribution along fixed edges
    first_cell_width                : 0.00001                             #first cell height when factor=1
    le_firstcellheight_coeff        : 1
    te_firstcellheight_coeff        : 1
    exp_ratio                       : 1.01                                  #expansion ratio along boundary layer
    layers                          : 1                                    #fixed cells in boundary layer
    extrudeLength                   : 0.04                                  #length of extruded span
    blockStartFromChord             : 0.015                                 #LE and TE-Block Meshing
    hk_ps_shift                     : 1                                     #LE and TE-Block Meshing
    hk_ss_shift                     : 1
    vk_ps_shift                     : 1                                     #LE and TE-Block Meshing
    vk_ss_shift                     : 1
    cellwidthcoeff                  : 0.001                                 #cell width-coeff at LT and TE (stagnation-point-flow)
    streamline_nodedensity_factor   : 1                                     #define node-density factor (in/outlet vs periodic)
    yPerLowHGridBlockPitchStart     : 0.3                                 #move low-y-per-block along y-pitch
    yPerHighHGridBlockPitchStart    : 0.7                                  #move high-y-per-block along y-pitch
    shift_vk_block_xaxiscoeff       : 0.05                                  #move periodic vertices (yPer from LE) along x
    shift_hk_block_xaxiscoeff       : -0.05                                 #move periodic vertices (yPer from TE) along x
    smoothing                       : 5000                                  #smoothing iterations
