geometry:
    beta_meta_01                    : 145 #138                                  #Inflow angle [deg]
    beta_meta_02                    : 115 #127                                   #Outflow angle [deg]
    pitch                           : 0.265                                #Pitch [m]
    alpha                           : 0.01                                  #Geometric parameter used for hull-calculations

probing:
    domain : "00_Ressources/02_UsedMesh/09_OpenFOAM_compCascade_0.vtk"
    blade : "00_Ressources/02_UsedMesh/BLADE_0.vtk"
    probes:
        massflow_probing: True
        residual_probing: True
        profile_probing: False
        fieldave_probing: True
        streamline_probing: False
        inletoutletvelocity_probing: False
        xslice_probing: False
        midspanslice_probing: False
    output_path : "02_Preprocessing/system"
