case_settings:
    name : "GWK_Verdichterkaskade_LES"
    case_type : "openfoam_cascade_les"

openfoam_cascade_les_settings:
    var_type : "openfoam_timeaverage"
    timestep : &timestep "10e-8"

simcase_settings:
    variables:
        CLUSTERJOBNAME: "gkw_p14profile_cascadecase_les"
        JOB_NUMBERS: "12"
        HLRN_JOB_ACCOUNT: "niinyhma"
        JOB_EMAIL: "nyhuis@tfd.uni-hannover.de"
        RUNTIME: "10:00:00"                                     #h
        NODES: "2"

        EDDYDENSITY: "10"
        UDASHSCALING: "1"
        TASKS_PER_NODE: "96"
        PINLET: "95000"                                         #Pa
        TINLET : "293.15"                                       #K
        TIN_LINF: "0.005"                                       #m
        UINLET: "35.392445 58.06355 0"                          #m/s
        UIN_LINF: "0.03"                                        #m
        RUNTIME: "10:00:00"
        NODES: "2"
        AVE_START: &AVE_START "0"

        RINLET : "4 0 0 4 0 4"                                  #m^2/s^2
        LINLET : "0.02"                                         #m

        POUTLET: "101325"
        POUT_LINF: "0.02"

        TOUTLET: "293.15"
        TOUT_LINF: "0.02"
        PITCHPER: "0.0765"
        SPANPER: "0.04"
        ZSPAN: "0.04"

        DELTAT: *timestep

        WRITEINTERVAL : "2000"
        PURGEWRITE: "2"

        ADUSTABLETIMESTEP : "off"
        PROCS: "192"
        NOUTERCORRECTORS : "2"

    options:
        INOUT_FIELDAVE_PROBING: True
        INOUT_VELOCITY_PROBING: True
        XSCLICE_PROBING : True
        MIDSPANSLICE_PROBING : True
        PROFILE_PROBING : True
        STREAMLINE_PROBING : True
        STAGNATIONPOINTFLOW_PROBING : True


simcase_optiondef:

    INOUT_VELOCITY_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createProbesInletOutlet"
        args:
            sampling_rate: 1e5 #Hz
            start_time: 0 #s
            end_time: 1000 #s
        insert: '#include "Probes_InletOutlet_Dict"'

    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_inletoutletave_probe_dict"
        args:
            sampling_rate: 1e5 #Hz
            start_time: 0
            end_time: 1000
        insert: '#include "Probes_inletoutletave_Dict"'

    XSCLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createXSliceProbes"
        args:
            nop: 3
            sampling_rate: 1e6 #Hz
            x_slice_one : -0.08
            x_slice_two : 0.18
            start_time: *AVE_START #s
            end_time: 1000 #s
        insert: '#include "Probes_XSlices_Dict"'

    PROFILE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createProbesProfileDict"
        args:
            pden_ps : 10
            pden_ss : 10
            sampling_rate : 1e6 #Hz
            start_time: *AVE_START #s
            end_time : 1000 #s
            tolerance : 0.000005
        insert: '#include "Probes_Profile_Dict"'


    STREAMLINE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createProbesStreamlineDict"
        args:
            nop_streamline : 20
            sampling_rate: 1e6 #Hz
            start_time: *AVE_START #s
            end_time: 1000 #s
        insert: '#include "Probes_Streamline_Dict"'

    STAGNATIONPOINTFLOW_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_vk_stagflow_probes"
        args:
            nop : 6
            sampling_rate: 1e5 #Hz
            length : 0.03 #m
            start_time: *AVE_START #s
            end_time: 1000 #s
        insert: '#include "Probes_VKstagnation_Dict"'

geometry:
    pitch                           : 0.0765                                #Pitch [m]
    alpha                           : 0.01                                  #Geometric parameter used for hull-calculations
    midline_tolerance               : 5                                     #Tolerance coefficient for midline-generation
    algorithm                       : "from_pointcloud"
    ptcloud_profile                 : "00_Ressources/profile_pointcloud.txt"   #Name of the pointcloud-file
    ptcloud_profile_unit            : "mm"                                  #m vs mm
    x_inlet                         : -0.13                                  #Shift Inlet along x [m]
    x_outlet                        : 0.26                              #Shift Outlet along x [m]
    shift_domain                    : 0.015                                 #Shift Domain to have probes inside domain [m]

mesh:
    factor                          : 1.04                                   #Mesh-density factor
    ogrid_factor                    : 5.5                                     #o-grid-node-ratio
    delta_i                         : 0.0015                                #node-distribution along fixed edges
    first_cell_width                : 0.0000070                             #first cell height when factor=1
    le_firstcellheight_coeff        : 0.8
    te_firstcellheight_coeff        : 0.8
    exp_ratio                       : 1.01                                  #expansion ratio along boundary layer
    layers                          : 10                                    #fixed cells in boundary layer
    extrudeLength                   : 0.04                                  #length of extruded span
    blockStartFromChord             : 0.011                                 #LE and TE-Block Meshing
    cellwidthcoeff                  : 0.4                                 #cell width-coeff at LT and TE (stagnation-point-flow)
    streamline_nodedensity_factor   : 1                                     #define node-density factor (in/outlet vs periodic)
    yPerLowHGridBlockPitchStart     : 0.2                                 #move low-y-per-block along y-pitch
    yPerHighHGridBlockPitchStart    : 0.5                                  #move high-y-per-block along y-pitch
    shift_vk_block_xaxiscoeff       : 0.045                                 #move periodic vertices (yPer from LE) along x
    shift_hk_block_xaxiscoeff       : 0.005                                 #move periodic vertices (yPer from TE) along x
    smoothing                       : 5000                                  #smoothing iterations
