case_settings:
    name : "GWK_Verdichterkaskade_LES"
    case_type : "CascadeCase"
    var_type : "openfoam_timeaverage"
    sim_type: "openfoam_les"
    machine_type : "compressor"
    timestep : "10e-8"

geometry:
    pitch                           : 0.0765                                #Pitch [m]
    alpha                           : 0.01                                  #Geometric parameter used for hull-calculations
    midline_tolerance               : 5                                     #Tolerance coefficient for midline-generation

probing:
    probes:
        profile_probing: True
        streamline_probing: True
        inletoutletfieldave_probing: True
        inletoutletvelocity_probing: True
        xslice_probing: True
        midspanslice_probing: True
        vk_stagnationflow_probing : True
    output_path : "02_Preprocessing/system"

monitoring:
    averagevaluesinlet: "/03_Solution/postProcessing/AverValuesInlet"
    averagevaluesoutlet: "/03_Solution/postProcessing/AverValuesOutlet"
    massflowinlet: "/03_Solution/postProcessing/MassflowInlet"
    massflowoutlet: "/03_Solution/postProcessing/MassflowOutlet"
    logfile: "03_Solution/log.log"

igg:
    install_directory               : "C:/NUMECA_SOFTWARE/fine121/bin64"
    executable                      : "iggx86_64.exe"
    argument_pickle_dict            : "igg_args.pkl"

geom:
    ptcloud_profile                 : "00_Ressources/01_Geometry/profile_pointcloud.txt"   #Name of the pointcloud-file
    ptcloud_profile_unit            : "mm"                                  #m vs mm
    x_inlet                         : -0.13                                  #Shift Inlet along x [m]
    x_outlet                        : 0.26                              #Shift Outlet along x [m]
    shift_domain                    : 0.015                                 #Shift Domain to have probes inside domain [m]

mesh:
    factor                          : 1.04                                   #Mesh-density factor
    ogrid_factor                    : 5.5                                     #o-grid-node-ratio
    delta_i                         : 0.0015                                #node-distribution along fixed edges
    first_cell_width                : 0.0000070                             #first cell height when factor=1
    le_firstcellheight_coeff        : 0.8
    te_firstcellheight_coeff        : 0.8
    exp_ratio                       : 1.01                                  #expansion ratio along boundary layer
    layers                          : 10                                    #fixed cells in boundary layer
    extrudeLength                   : 0.04                                  #length of extruded span
    blockStartFromChord             : 0.011                                 #LE and TE-Block Meshing
    cellwidthcoeff                  : 0.4                                 #cell width-coeff at LT and TE (stagnation-point-flow)
    streamline_nodedensity_factor   : 1                                     #define node-density factor (in/outlet vs periodic)
    yPerLowHGridBlockPitchStart     : 0.2                                 #move low-y-per-block along y-pitch
    yPerHighHGridBlockPitchStart    : 0.5                                  #move high-y-per-block along y-pitch
    shift_vk_block_xaxiscoeff       : 0.045                                 #move periodic vertices (yPer from LE) along x
    shift_hk_block_xaxiscoeff       : 0.005                                 #move periodic vertices (yPer from TE) along x
    smoothing                       : 5000                                  #smoothing iterations


case:
    case_parameters:
      U :
        UINLET : "35.392445 58.06355 0"
        RINLET : "4 0 0 4 0 4"
        LINLET : "0.02"
        EDDYDENSITY : "10"
        UDASHSCALING : "1"
      T :
        TINLET : "293.15"
      p :
        PINLET : "101325"
      alphat:
      nut:
      thermophysicalProperties:
      turbulenceProperties:
      controlDict:
        WRITEINTERVAL : "2000"
        ADUSTABLETIMESTEP : "off"
        STARTAVETIME : "0.12"
      createPatchDict:
      decomposeParDict:
        PROCS: "192"
      fvSchemes:
      fvSolution:
          NOUTERCORRECTORS : "2"
      mapFieldsDict:
      SurfaceSampleDict:
      topoSetDict:

      Probes_FieldAve_Dict:
          START: "0.12"
          END: "1000"
      Probe_Slice_Dict:
          START: "0.12"
          END: "1000"

      submit_job_hlrn.sh:
          RUNTIME : "10:00:00"
          NODES: "2"
          PROCS: "192"

probes:
    profile_probes:
        pden_ps : 10
        pden_ss : 10
        sampling_rate : 1e6 #Hz
        start_time : 0.12 #s
        end_time : 1000 #s
        tolerance : 0.000005

    streamline_probes:
        nop_streamline : 20
        sampling_rate: 1e6 #Hz
        start_time: 0.12 #s
        end_time: 1000 #s

    inletoutlet_probes:
        mesh : domain
        sampling_rate: 1e5 #Hz
        start_time: 0 #s
        end_time: 1000 #s

    inletoutletfieldave_probing:
        sampling_rate: 1e5 #Hz
        start_time: 0
        end_time: 1000

    xsclicing_probes:
        mesh : domain
        nop: 6
        sampling_rate: 1e5 #Hz
        x_slice_one : -0.08
        x_slice_two : 0.18
        start_time: 0 #s
        end_time: 0.12 #s

    vk_stagnationflow_probing:
        nop : 6
        sampling_rate: 1e5 #Hz
        length : 0.03 #m
        start_time: 0.12 #s
        end_time: 1000 #s
