case_settings:
    name : &name "GWK_Verdichterkaskade_LES"
    case_type : "openfoam_cascade_les"
    type: "simulation"
    prep : |
        cp ../01_Meshing/fluent.msh .
        fluent3DMeshToFoam fluent.msh
        createPatch -overwrite
        topoSet
        #mapFields /scratch/usr/niinyhma/14_CascadeCase_gwk_les/02_Simcase -sourceTime 'latestTime' -consistent
        decomposePar
        dos2unix submit_mpi_job_slurm_hlrn.sh

    job:
        job_mail: "nyhuis@tfd.uni-hannover.de"
        job_script: "submit_mpi_job_slurm_hlrn"
        job_sourcecmd: |
            module load  gcc/7.5.0 cmake/3.16.2; source /home/niikceng/OpenFOAM/OpenFOAM-v1612+/etc/bashrc
            export FOAM_USER_PATH='$HOME/OpenFOAM/niinyhma-v1612+/'
            #. $MODULESHOME/init/ksh
            #source ~/ModuleLoading/OpenFoam1612.sh

        job_exe: "rhoPimpleFoam"
        job_name: *name
        job_runtime: "10:00:00" #h
        job_nodes : "2"
        job_ppn : "96"
        job_mem : "192"
        job_account : "niinyhma"

    sub_cmd: "sbatch"

openfoam_cascade_les_settings:
    var_type : "openfoam_timeaverage"
    timestep : &timestep "4e-8"

simcase_settings:
    variables:

        DYNVISK: "20e-6"
        EDDYDENSITY: "1"
        UDASHSCALING: "1"
        TASKS_PER_NODE: "96"

        RUNTIME: "10:00:00"
        NODES: "2"
        AVE_START: &AVE_START "0.0"

        PINLET: "95000"                                         #Pa
        TINLET : "293.15"                                       #K
        TIN_LINF: "0.02"                                       #m
        UINLET: "51.2137514 44.73423373 0"                          #m/s
        UIN_LINF: "0.02"                                        #m
        RINLET : "4 0 0 4 0 4"                                  #m^2/s^2
        LINLET : "0.02"                                         #m

        POUTLET: "101325"
        POUT_LINF: "0.01"
        TOUTLET: "293.15"
        TOUT_LINF: "0.01"

        PITCHPER: "0.0765"
        ZSPAN: "0.04"

        DELTAT: *timestep
        MAX_CFL: "0.4"

        WRITEINTERVAL : "2000"
        PURGEWRITE: "2"

        ADUSTABLETIMESTEP : "off"
        TIMEDTTSCHEME : "Euler"

        PROCS: "192"

        NOUTERCORRECTORS : "2"
        NCORRECTORS : "2"
        NNONORTHOGONALCORRECTORS: "2"

    options:
        INOUT_FIELDAVE_PROBING: True
        INOUT_VELOCITY_PROBING: True
        XSCLICE_PROBING : True
        SLICE_PROBING : True
        PROFILE_PROBING : True
        STREAMLINE_PROBING : True
        STAGNATIONPOINTFLOW_PROBING : True


simcase_optiondef:

    INOUT_VELOCITY_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createProbesInletOutlet"
        args:
            sampling_rate: 1e5 #Hz
            start_time: 0 #s
            end_time: 1000 #s
        insert: '#include "Probes_InletOutlet_Dict"'

    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_inletoutletave_probe_dict"
        args:
            fields: "(U p T)"
            sampling_rate: 1e5 #Hz
            start_time: 0
            end_time: 1000
        insert: '#include "Probes_inletoutletave_Dict"'

    XSCLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createXSliceProbes"
        args:
            nop: 3
            sampling_rate: 1e6 #Hz
            x_slice_one : -0.08
            x_slice_two : 0.18
            start_time: *AVE_START #s
            end_time: 1000 #s
        insert: '#include "Probes_XSlices_Dict"'

    PROFILE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createProbesProfileDict"
        args:
            pden_ps : 10
            pden_ss : 10
            sampling_rate : 1e6 #Hz
            start_time: *AVE_START #s
            end_time : 1000 #s
            tolerance : 0.000005
        insert: '#include "Probes_Profile_Dict"'

    STREAMLINE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createProbesStreamlineDict"
        args:
            nop_streamline : 20
            sampling_rate: 1e6 #Hz
            start_time: *AVE_START #s
            end_time: 1000 #s
        insert: '#include "Probes_Streamline_Dict"'

    STAGNATIONPOINTFLOW_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_vk_stagflow_probes"
        args:
            nop : 6
            sampling_rate: 1e5 #Hz
            length : 0.03 #m
            start_time: *AVE_START #s
            end_time: 1000 #s
        insert: '#include "Probes_VKstagnation_Dict"'

    SLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openfoam_createSlicingDict"
        args:
            fields: "(U p)"
            origin: "(0 0 0.02)"
            normal: "(0 0 1)"
            sampling_rate: 4e4
            start_time:  *AVE_START #s
            end_time: 1000
        insert: '#include "Probes_Slicing_Dict"'

geometry:
    pitch                           : 0.0765                                #Pitch [m]
    alpha                           : 0.01                                  #Geometric parameter used for hull-calculations
    midline_tolerance               : 5                                     #Tolerance coefficient for midline-generation
    algorithm                       : "from_pointcloud"
    ptcloud_profile                 : "00_Ressources/profile_pointcloud.txt"   #Name of the pointcloud-file
    ptcloud_profile_unit            : "mm"                                  #m vs mm
    x_inlet                         : -0.13                                 #Shift Inlet along x [m]
    x_outlet                        : 0.26                                  #Shift Outlet along x [m]
    shift_domain                    : 0.015                                 #Shift Domain to have probes inside domain [m]

mesh:
    factor                          : 0.6                                   #Mesh-density factor
    ogrid_factor                    : 5                                   #o-grid-node-ratio
    delta_i                         : 0.0005                                #node-distribution along fixed edges
    first_cell_width                : 0.000015                               #first cell height when factor=1
    le_firstcellheight_coeff        : 1
    te_firstcellheight_coeff        : 1
    exp_ratio                       : 1.01                                  #expansion ratio along boundary layer
    layers                          : 18                                    #fixed cells in boundary layer
    extrudeLength                   : 0.04                                  #length of extruded span
    blockStartFromChord             : 0.015                                 #LE and TE-Block Meshing
    cellwidthcoeff                  : 0.1                                 #cell width-coeff at LT and TE (stagnation-point-flow)
    streamline_nodedensity_factor   : 1                                     #define node-density factor (in/outlet vs periodic)
    yPerLowHGridBlockPitchStart     : 0.2                                 #move low-y-per-block along y-pitch
    yPerHighHGridBlockPitchStart    : 0.5                                  #move high-y-per-block along y-pitch
    shift_vk_block_xaxiscoeff       : 0.045                                 #move periodic vertices (yPer from LE) along x
    shift_hk_block_xaxiscoeff       : 0.005                                 #move periodic vertices (yPer from TE) along x
    smoothing                       : 5000                                  #smoothing iterations


post_settings:
    use_vtk_meshes:
        volmesh: "VTK/02_Simcase_216000.vtk"
        wallpatches:
            blade: "VTK/BLADE/BLADE_216000.vtk"

    dimensionless_gridspacing:
        use_velfield: "U"
        use_rhofield: "rho"

    yplus_calc:
        use_velfield: "U"
        use_rhofield: "rho"

    profile_loading:
        volmesh: "VTK/02_Simcase_224000.vtk"

    animation_creation:
        cpos                        : [0,0,1]

#        variable                    : "p"
#        low_scale_limit             : 90000
#        high_scale_limit            : 120000
#        resolution_x                : 2600
#        resolution_y                : 2600

        variable                    : "U"
        low_scale_limit             : 0
        high_scale_limit            : 90
        resolution_x                : 2600
        resolution_y                : 2600