case_name : "OpenFOAM_compCascade"
case_parameters:
  U :
    UINLET : "35.392445 58.06355 0"
    RINLET : "2 0 0 2 0 2"
    LINLET : "0.02"
    EDDYDENSITY : "10"
  T :
    TINLET : "293.15"
  p :
    PINLET : "101325"
  alphat:
  nut:
  thermophysicalProperties:
  turbulenceProperties:
  controlDict:
    WRITEINTERVAL : "2000"
    DELTAT : "5e-8"
    ADUSTABLETIMESTEP : "on"
    STARTAVETIME : "0.045"
  createPatchDict:
  decomposeParDict:
    PROCS: "384"
  fvSchemes:
  fvSolution:
  mapFieldsDict:
  SurfaceSampleDict:
  topoSetDict:

  submit_job_hlrn.sh:
      RUNTIME : "05:00:00"
      NODES: "4"
      PROCS: "384"
  monitor.py:
