case:
    case_parameters:
      U :
        UINLET : "35.392445 58.06355 0"
        RINLET : "2 0 0 2 0 2"
        LINLET : "0.01"
        EDDYDENSITY : "10"
      T :
        TINLET : "293.15"
      p :
        PINLET : "101325"
      alphat:
      nut:
      thermophysicalProperties:
      turbulenceProperties:
      controlDict:
        WRITEINTERVAL : "2000"
        DELTAT : "5e-8"
        ADUSTABLETIMESTEP : "on"
        STARTAVETIME : "0.045"
      createPatchDict:
      decomposeParDict:
        PROCS: "384"
      fvSchemes:
      fvSolution:
      mapFieldsDict:
      SurfaceSampleDict:
      topoSetDict:

      Probes_FieldAve_Dict:
          START: "0.12"
          END: "1000"
      Probe_Slice_Dict:
          START: "0.12"
          END: "1000"

      submit_job_hlrn.sh:
          RUNTIME : "05:00:00"
          NODES: "4"
          PROCS: "384"
      monitor.py:

probes:
    profile_probes:
        pden_ps : 20
        pden_ss : 20
        interval_time_steps_probes : 1
        start_time : 0.12
        end_time : 1000
        tolerance : 0.0005

    streamline_probes:
        nop_streamline : 20
        interval_time_steps_probes : 1
        start_time: 0.12
        end_time: 1000

    inletoutlet_probes:
        mesh : domain
        interval_time_steps_probes: 1
        start_time: 0
        end_time: 1000

    xsclicing_probes:
        mesh : domain
        nop: 10
        interval_time_steps_probes: 1
        x_slice_one : -0.08
        x_slice_two : 0.18
        start_time: 0.12
        end_time: 1000

