case_settings:
    name : &name "GWK_Verdichterkaskade_TRACE_RAS"
    case_type : "trace_cascade_ras"
    type: "simulation"
    description: |
        mesh-status:
            good quality mesh
            no meshstudy until now
        boundarycondition-status:
            bc not evaluated
        solution-status:
            stable solution?
        postprocessing-status:
            need of more postprocessing and evaluation methods
    prep: |
        cp ../01_Meshing input/.
        cd input/
        gmcplay verdichter.jou
        cd ..
    job:
        job_mail: "nyhuis@tfd.uni-hannover.de"
        job_script: "submit_mpi_job_trace_sp_pbs"
        job_sourcecmd: |
            TRACEown

        job_exe: "TRACE"
        job_name: *name
        job_runtime: "10:00:00" #h
        job_nodes : "1"
        job_ppn : "1"
        job_mem : "12"
        account : "nhkcmany"

    fluid:
        kappa: "1.4"
        molar_weight_M: &molar_weight_M "28.96"
        R_L: "287.05"
        mu: "20.0e-6"
        As: "1.458e-06"
        cp: "1004.5"
        Ts: "110.4"
        p_k: "95000.0"
    sub_cmd: "sh"

simcase_settings:
    variables:

        TURBMODEL_IDENTIFIER: "Wilcox1988"   # MenterSST2003 // Wilcox1988

        ACCURACY_ORDER: "2ndOrder"
        STAGPOINT_ANNOMALLYFIX: "KatoLaunder"
        QUASIUNSTEADYMODEL: "Off"
        WAVINESSMODEL: "Off"
        VERSION_TWONULLNULLNINE: "Off"
        HEATFLUXMODEL: "ConstantPrandtl"
        PRANDTLTURBULENT: "0.900000"
        ROTATIONAL_EFF: "Off"
        TRANSITIONMODEL: "Off"
        VGJMODEL: "Null"

        LENGTH_YPER: "0.0765"

        INLET_TOTAL_PRESSURE: "101325"
        INLET_TEMP: "293.15"
        INLET_VELX: "35.392445"
        INLET_VELY: "58.06355"
        INLET_VELZ: "0"

        OUTLET_MFLOW: "0.010791667"
        OUTFLOW_PRESSURE: "100000"
        OUTFLOW_TEMP: "293.15"
        OUTFLOW_VELX: "35.392445"
        OUTFLOW_VELY: "40"
        OUTFLOW_VELZ: "0"

        VEL_YANGLE: "48.05"
        GLOBAL_TOLERANCE: "0.0000001"

        TRACE_CONTROLINPUT: |
            #all immediate ChangeTurbulenceSettings --model MNEDITWilcox1988
            #all immediate Update_kw_tdr_tdp tdr_param "0.8"
            #all immediate Update_kw_tdr_tdp tpr_param "1.2"

    options:
simcase_optiondef:

geometry:
    pitch                           : 0.0765                                #Pitch [m]
    alpha                           : 0.01                                  #Geometric parameter used for hull-calculations
    algorithm                       : "from_pointcloud"
    ptcloud_profile                 : "00_Ressources/profile_pointcloud.txt"              #Name of the pointcloud-file
    ptcloud_profile_unit            : "mm"                                   #m vs mm
    x_inlet                         : -0.1                                  #Shift Inlet along x [m]
    x_outlet                        : 0.27                                  #Shift Outlet along x [m]
    pitch                           : 0.0765                                #Pitch [m]
    shift_domain                    : 0.01                                 #Shift Domain to have probes inside domain [m]

mesh:
    factor                          : 1.7                                   #Mesh-density factor
    ogrid_factor                    : 4                                 #o-grid-node-ratio
    delta_i                         : 0.0015                                #node-distribution along fixed edges
    first_cell_width                : 0.0000075                              #first cell height when factor=1
    le_firstcellheight_coeff        : 0.4
    te_firstcellheight_coeff        : 0.8
    exp_ratio                       : 1.01                                  #expansion ratio along boundary layer
    layers                          : 2                                     #fixed cells in boundary layer
    extrudeLength                   : 0.0025                                  #length of extruded span
    blockStartFromChord             : 0.015                                 #LE and TE-Block Meshing
    cellwidthcoeff                  : 0.001                                #cell width-coeff at LT and TE (stagnation-point-flow)
    streamline_nodedensity_factor   : 1                                   #define node-density factor (in/outlet vs periodic)
    yPerLowHGridBlockPitchStart     : 0.3                                 #move low-y-per-block along y-pitch
    yPerHighHGridBlockPitchStart    : 0.6                                  #move high-y-per-block along y-pitch
    shift_vk_block_xaxiscoeff       : 0.0475                                  #move periodic vertices (yPer from LE) along x
    shift_hk_block_xaxiscoeff       : 0.0                                  #move periodic vertices (yPer from TE) along x
    smoothing                       : 5000                                  #smoothing iterations

post_settings:
    solution                     : "03_Solution/TRACE.cgns"
    post_func_data:
        measureplane_slices:
                x_pos_1 : 0.01
                x_pos_2 : 0.25
    call_funcs:
        - profile_data
