case_settings:
    name : &name "channelflow_les"
    case_type : "openfoam_channel_les"
    type: "simulation"
    prep: |
        blockMesh
        createPatch -overwrite
        decomposePar
        dos2unix submit_mpi_job_slurm_rrzn.sh
    job:
        job_mail: "nyhuis@tfd.uni-hannover.de"
        job_script: "submit_mpi_job_slurm_rrzn"
        job_sourcecmd: |
            . $MODULESHOME/init/ksh
            source ~/ModuleLoading/OpenFoam1612.sh

        job_exe: "pimpleFoam"
        job_name: *name
        job_runtime: "10:00:00" #h
        job_nodes : "1"
        job_ppn : "16"
        job_mem : "12"
        account : "niinyhma"

    sub_cmd : "sbatch"

openfoam_cascade_les_settings:
    timestep : &timestep "0.5"

simcase_settings:
    variables:

        DELTAT: *timestep
        MAX_CFC: "0.4"
        WRITEINTERVAL : "200"
        PURGEWRITE: "2"

        ADUSTABLETIMESTEP : "on"

        MESH_SCALING : 0.5
        GEO_LENGTH : &GEO_LENGTH "10"
        GEO_WIDTH :  &GEO_WIDTH "3"
        GEO_HALFHEIGHT : &GEO_HALFHEIGHT "0.5"

        PROCS : 16
    options:
        INOUT_FIELDAVE_PROBING: True
        XSCLICE_PROBING: True
        SLICE_PROBING: True

geometry:
    algorithm: "prep"
    channel_length : *GEO_LENGTH
    yper_width : *GEO_WIDTH
    channel_halfheight : *GEO_HALFHEIGHT

simcase_optiondef:
    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_inletoutletave_probe_dict"
        args:
            fields: "(U p)"
            sampling_rate: 1e5 #Hz
            start_time: 0
            end_time: 1000
        insert: '#include "Probes_inletoutletave_Dict"'

    XSCLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createXSliceProbes"
        args:
            nop: 3
            sampling_rate: 1e6 #Hz
            x_slice_one : 1
            x_slice_two : 9
            start_time: 0.0 #s
            end_time: 1000 #s
        insert: '#include "Probes_XSlices_Dict"'

    SLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openfoam_createSlicingDict"
        args:
            fields: "(U p)"
            origin : "(0 0 0.5)"
            normal : "(0 0 1)"
            sampling_rate: 1e0
            start_time: 0 # *AVE_START #s
            end_time: 1000
        insert: '#include "Probes_Slicing_Dict"'

post_settings:
    dimensionless_gridspacing:
        volmesh                     : "03_Solution/volume.vtk"
        wall                        : "03_Solution/surface.vtk"
    profile_loading:
        volmesh                     : "03_Solution/volume.vtk"

    animation_creation:
        variable                    : "U"
