case_settings:
    name : "Channel_LES"
    case_type : "openfoam_channel_les"

openfoam_cascade_les_settings:
    timestep : "10e-8"

simcase_settings:
    variables:
        CLUSTERJOBNAME: "channelflow_les"
        TASKS_PER_NODE: "16"
        NODES: "3"
        PROCS: "48"

        HLRN_JOB_ACCOUNT: "niinyhma"
        RRZN_JOB_ACCOUNT: "nhkcmany"
        JOB_EMAIL: "nyhuis@tfd.uni-hannover.de"
        TASKS_PER_NODE: "16"
        WALLTIME: "16:00:00"
        MEMORY: "16gb"
        DELTAT: "0.05"
        WRITEINTERVAL : "200"
        PURGEWRITE: "2"

        ADUSTABLETIMESTEP : "off"

        GEO_LENGTH : &GEO_LENGTH "25.1327412287183459"
        GEO_WIDTH :  &GEO_WIDTH "9.4247779607693"
        GEO_HALFHEIGHT : &GEO_HALFHEIGHT "1.0"

    options:
        INOUT_FIELDAVE_PROBING: True
        XSCLICE_PROBING: True

geometry:
    algorithm: "prep"
    channel_length : *GEO_LENGTH
    yper_width : *GEO_WIDTH
    channel_halfheight : *GEO_HALFHEIGHT

simcase_optiondef:
    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_inletoutletave_probe_dict"
        args:
            sampling_rate: 1e5 #Hz
            start_time: 0
            end_time: 1000
        insert: '#include "Probes_inletoutletave_Dict"'

    XSCLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createXSliceProbes"
        args:
            nop: 3
            sampling_rate: 1e6 #Hz
            x_slice_one : 1
            x_slice_two : 25
            start_time: 0.0 #s
            end_time: 1000 #s
        insert: '#include "Probes_XSlices_Dict"'