case_settings:
    name : "Channel_LES"
    case_type : "openfoam_channel_les"

openfoam_cascade_les_settings:
    timestep : "10e-8"

simcase_settings:
    variables:
        CLUSTERJOBNAME: "channelflow_les"
        JOB_NUMBERS: "16"
        HLRN_JOB_ACCOUNT: "niinyhma"
        RRZN_JOB_ACCOUNT: "nhkcmany"
        JOB_EMAIL: "nyhuis@tfd.uni-hannover.de"
        NODES: "1"
        TASKS_PER_NODE: "16"
        WALLTIME: "16:00:00"
        MEMORY: "16gb"
        DELTAT: "0.05"
        WRITEINTERVAL : "200"
        PURGEWRITE: "2"

        ADUSTABLETIMESTEP : "off"

    options:
        INOUT_FIELDAVE_PROBING: True
        XSCLICE_PROBING: True

simcase_optiondef:
    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_inletoutletave_probe_dict"
        args:
            sampling_rate: 1e5 #Hz
            start_time: 0
            end_time: 1000
        insert: '#include "Probes_inletoutletave_Dict"'

    XSCLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createXSliceProbes"
        args:
            nop: 3
            sampling_rate: 1e6 #Hz
            x_slice_one : -0.08
            x_slice_two : 0.18
            start_time: 0.0 #s
            end_time: 1000 #s
        insert: '#include "Probes_XSlices_Dict"'