case_settings:
    name : "Channel_LES"
    case_type : "openfoam_channel_les"

openfoam_cascade_les_settings:
    timestep : "10e-8"

simcase_settings:
    variables:
        CLUSTERJOBNAME: "channelflow_les"
        JOB_NUMBERS: "12"
        HLRN_JOB_ACCOUNT: "niinyhma"
        RRZN_JOB_ACCOUNT: "nhkcmany"
        JOB_EMAIL: "nyhuis@tfd.uni-hannover.de"
        NODES: "8"
        TASKS_PER_NODE: "24"
        WALLTIME: "10:00:00"
        MEMORY: "16gb"


    options:
        INOUT_FIELDAVE_PROBING: True

simcase_optiondef:
    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.create_simcase_options.openFoam_create_inletoutletave_probe_dict"
        args:
            sampling_rate: 1e5 #Hz
            start_time: 0
            end_time: 1000
        insert: '#include "Probes_inletoutletave_Dict"'
