case_settings:
    name : &name "channelflow_les"
    case_type : "openfoam_channel_les"
    type: "simulation"
    description: |
        mesh-status:
            good quality mesh
            no meshstudy until now
            mesh only for test-cases
        boundarycondition-status:
            bc randomly set
        solution-status:
            stable solution
        postprocessing-status:
            need of more postprocessing and evaluation methods
    prep: |
        blockMesh
        createPatch -overwrite
        decomposePar
        dos2unix submit_mpi_pbs_rrzn.sh
    job:
        job_mail: "nyhuis@tfd.uni-hannover.de"
        job_script: "submit_mpi_pbs_rrzn"
        job_sourcecmd: |
            . $MODULESHOME/init/ksh
            source ~/ModuleLoading/OpenFoam1612.sh

        job_exe: "pimpleFoam"
        job_name: *name
        job_runtime: "10:00:00" #h
        job_nodes : "1"
        job_ppn : "16"
        job_mem : "12"
        account : "niinyhma"

    sub_cmd : "qsub"

openfoam_cascade_les_settings:
    timestep : &timestep "0.5"

simcase_settings:
    variables:
        UMEAN: "1"
        DYNVISK: "3.5e-04" #ACHTUNG, DAS HIER IST NICHT DIE DYNAMISCHE VISKOSITÄT
        DELTAT: *timestep
        AVE_START: &AVE_START "10"
        MAX_CFL: "0.4"
        WRITEINTERVAL: "200"
        PURGEWRITE: "2"

        ADUSTABLETIMESTEP : "on"

        MESH_SCALING : 0.5
        GEO_LENGTH : &GEO_LENGTH "5"
        GEO_WIDTH :  &GEO_WIDTH "3"
        GEO_HALFHEIGHT : &GEO_HALFHEIGHT "0.5"

        PROCS : 16
    options:
        INOUT_FIELDAVE_PROBING: True
        XSCLICE_PROBING: True
        SLICE_PROBING: True

geometry:
    algorithm: "prep"
    channel_length : *GEO_LENGTH
    yper_width : *GEO_WIDTH
    channel_halfheight : *GEO_HALFHEIGHT

simcase_optiondef:
    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_inletoutletave_probe_dict"
        args:
            fields: "(U p)"
            sampling_rate: 1e5 #Hz
            start_time: 0
            end_time: 1000
        insert: '#include "Probes_inletoutletave_Dict"'

    XSCLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createXSliceProbes"
        args:
            nop: 3
            sampling_rate: 1e6 #Hz
            x_slice_one : 1
            x_slice_two : 9
            start_time: 0.0 #s
            end_time: 1000 #s
        insert: '#include "Probes_XSlices_Dict"'

    SLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openfoam_createSlicingDict"
        args:
            fields: "(U p)"
            origin : "(0 0 0.5)"
            normal : "(0 0 1)"
            sampling_rate: 0.01
            start_time: *AVE_START #s
            end_time: 1000
        insert: '#include "Probes_Slicing_Dict"'

post_settings:
    use_vtk_meshes:
        volmesh: "VTK/02_Simcase_404800.vtk"
        wallpatches:
            buttomWall: "VTK/bottomWall/bottomWall_404800.vtk"
            topWall: "VTK/topWall/topWall_404800.vtk"

    dimensionless_gridspacing:
        use_velfield: "U"
        use_rhofield: "rho"

    yplus_calc:
        use_velfield: "U"
        use_rhofield: "rho"

    animation_creation:
        variable                    : "U"
        low_scale_limit             : 0
        high_scale_limit            : 2
        resolution_x                : 2600
        resolution_y                : 2600

    average_volumeonline:
        line_dir : y
