case_settings:
    name : &name "channelflow_les"
    case_type : "openfoam_channel_les_dfsem_compressible"
    type: "simulation"
    description: |
        mesh-status:
            good quality mesh
            no meshstudy until now
            mesh only for test-cases
        boundarycondition-status:
            bc randomly set
            fitting cfl
        solution-status:
            stable solution
        postprocessing-status:
            this sim is used to define new postprocessing methods
    prep: |
        blockMesh
        createPatch -overwrite
        mapFields ../../06_ChannelCase_les/02_Simcase/ -sourceTime 'latestTime' -consistent
        decomposePar
        dos2unix submit_mpi_job_slurm_rrzn.sh
    job:
        job_mail: "nyhuis@tfd.uni-hannover.de"
        job_script: "submit_mpi_job_slurm_rrzn"
        job_sourcecmd: |
            . $MODULESHOME/init/ksh
            source ~/ModuleLoading/OpenFoam1612.sh

        job_exe: "pimpleFoam"
        job_name: *name
        job_runtime: "10:00:00" #h
        job_nodes : "2"
        job_ppn : "16"
        job_mem : "32"
        account : "niinyhma"

    sub_cmd : "qsub"

openfoam_cascade_les_settings:
    timestep : &timestep "0.003"

simcase_settings:
    variables:
        UMEAN: "1"
        DYNVISK: "3.5e-04" #ACHTUNG, DAS HIER IST NICHT DIE DYNAMISCHE VISKOSITÄT
        DELTAT: *timestep
        AVE_START: &AVE_START "0"
        MAX_CFL: "0.75"
        WRITEINTERVAL: "1000"
        PURGEWRITE: "2"

        ADUSTABLETIMESTEP : "off"
        TIMEDTTSCHEME : "backward"

        NOUTERCORRECTORS: "1"
        NCORRECTORS: "2"
        NNONORTHOGONALCORRECTORS: "0"

        MESH_SCALING : 0.05
        GEO_LENGTH : &GEO_LENGTH "5"
        GEO_WIDTH :  &GEO_WIDTH "3"
        GEO_HALFHEIGHT : &GEO_HALFHEIGHT "0.5"

        PROCS : 16
    options:
        INOUT_FIELDAVE_PROBING: True
        XSCLICE_PROBING: True
        SLICE_PROBING: True
        STREAMLINE_PROBING: True

geometry:
    algorithm: "prep"
    channel_length : *GEO_LENGTH
    yper_width : *GEO_WIDTH
    channel_halfheight : *GEO_HALFHEIGHT

simcase_optiondef:
    INOUT_FIELDAVE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_create_inletoutletave_probe_dict"
        args:
            fields: "(U p)"
            sampling_rate: 10 #Hz
            start_time: 0
            end_time: 100000000
        insert: '#include "Probes_inletoutletave_Dict"'

    XSCLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createXSliceProbes"
        args:
            nop: 3
            sampling_rate: 10 #Hz
            x_slice_one : 1
            x_slice_two : 4
            start_time: 0.0 #s
            end_time: 100000000 #s
        insert: '#include "Probes_XSlices_Dict"'

    SLICE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openfoam_createSlicingDict"
        args:
            fields: "(U p)"
            origin : "(0 0 0.5)"
            normal : "(0 0 1)"
            sampling_rate: 10
            start_time: *AVE_START #s
            end_time: 100000000
        insert: '#include "Probes_Slicing_Dict"'

    STREAMLINE_PROBING:
        func: "NTR.preprocessing.options.openfoam.openFoam_createProbesStreamlineDict"
        args:
            fields: "(U p)"
            nop_streamline: 20
            sampling_rate: 10 #Hz
            start_time: *AVE_START #s
            end_time: 100000000 #s
        insert: '#include "Probes_Streamline_Dict"'

post_settings:
    use_vtk_meshes:
        volmesh: "VTK/02_Simcase_88000.vtk"
        wallpatches:
            buttomWall: "VTK/bottomWall/bottomWall_88000.vtk"
            topWall: "VTK/topWall/topWall_88000.vtk"

    dimensionless_gridspacing:
        use_velfield: "U"
        use_rhofield: "rho"

    yplus_calc:
        use_velfield: "U"
        use_rhofield: "rho"

    animation_creation:
        variable                    : "U"
        cpos                        : [0,0,1]
        low_scale_limit             : 0
        high_scale_limit            : 2
        resolution_x                : 2600
        resolution_y                : 2600

    average_volumeonline:
        line_dir : y

    average_volumeonplane:
        line_dir: y
        cellcentered: True

