geometry:
    pitch                           : 0.1524                                #Pitch [m]
    alpha                           : 0.03                                  #Geometric parameter used for hull-calculations
    midline_tolerance               : 20

geom:
    algorithm                       : "from_pointcloud"
    ptcloud_profile                 : "00_Ressources/PointCloudBladeGeometry.txt"              #Name of the pointcloud-file
    ptcloud_profile_unit            : "mm"                                   #m vs mm
    x_inlet                         : -0.16                                  #Shift Inlet along x [m]
    x_outlet                        : 0.32                                  #Shift Outlet along x [m]
    shift_domain                    : 0.0

mesh:
    factor                          : 1                                   #Mesh-density factor
    ogrid_factor                    : 1.6                                   #o-grid-node-ratio
    delta_i                         : 0.0015                                #node-distribution along fixed edges
    first_cell_width                : 0.000005                              #first cell height when factor=1
    le_firstcellheight_coeff        : 0.5
    te_firstcellheight_coeff        : 0.5
    exp_ratio                       : 1.01                                  #expansion ratio along boundary layer
    layers                          : 2                                     #fixed cells in boundary layer
    extrudeLength                   : 0.006                                  #length of extruded span
    blockStartFromChord             : 0.015                                 #LE and TE-Block Meshing
    cellwidthcoeff                  : 0.001                                #cell width-coeff at LT and TE (stagnation-point-flow)
    streamline_nodedensity_factor   : 1                                   #define node-density factor (in/outlet vs periodic)
    yPerLowHGridBlockPitchStart     : 0.35                                   #move low-y-per-block along y-pitch
    yPerHighHGridBlockPitchStart    : 0.8                                  #move high-y-per-block along y-pitch
    shift_vk_block_xaxiscoeff       : 0.0                                  #move periodic vertices (yPer from LE) along x
    shift_hk_block_xaxiscoeff       : 0.05                                  #move periodic vertices (yPer from TE) along x
    smoothing                       : 5000                                  #smoothing iterations
