case_settings:
    name : &name "VerginiaTech_TRACE_RAS"
    case_type : "trace_virginiatech_SEC_PARASTUD"
    type: "parameterstudy"
    description: |
        mesh-status:
            good quality mesh
            meshstudy is done
        boundarycondition-status:
            evaluated by RWTH AACHEN
        solution-status:
            model working
        postprocessing-status:
            need of more postprocessing and evaluation methods
    prep: |
        cp ../../00_Ressources/VT.cgns input/TRACE.cgns
        dos2unix submit_mpi_job_trace_sp_pbs_controlinput.sh
        cd input/
        /bigwork/nhkckcen/sw/GMC/gmc_9_3_4/gmcPlay_v9_3_4 virginiatech.jou
        cd ..
    job:
        job_mail: "nyhuis@tfd.uni-hannover.de"
        job_script: "submit_mpi_job_trace_sp_pbs_controlinput"
        job_exe: "TRACE"
        job_name: *name
        job_runtime: "30:00:00" #h
        job_nodes : "4"
        job_ppn : "12"
        job_mem : "24"
        account : "niinyhma"
    sub_cmd : "sh"

simcase_settings:
    variables:

        SECDEV_TDR: 1
        SECDEV_TPR:
            - 0.8
            - 1.2
        CLEARANCE_TDR: 1
        CLEARANCE_TPR: 1
        INLETANGLE:
            - 60.00
            - 61.00
            - 62.00
            - 63.00
            - 64.00
            - 65.00
            - 66.00

    options:
        simcase_optiondef:

