case_settings:
    name : "GWK_Verdichterkaskade_LES"
    case_type : "CascadeCase"
    var_type : "openfoam_instantanious"
    sim_type: "haha"
    machine_type : "compressor"

mesh_dict:
    fluid : "./02_Solution/06_GWKVD_RANS_22900.vtk"
    blade : "./02_Solution/BLADE/BLADE_22900.vtk"

post_process_settings:
    calc_gradients :
        mesh : "fluid"
        scalar : "U"
    set_xs:
        set_x1: -0.08
        set_x2 : 0.2
    alpha : 0.2

fluid_coeffs:
    kappa : 1.4
    M : 28.86e-3
    mu : 20.0e-6
    As : 1.458e-06
    cp : 1004.5
    Ts : 110.4
    l : 0.13
    p_k : 95000.0

