igg:
    install_directory               : "C:/NUMECA_SOFTWARE/fine121/bin64"
    executable                      : "iggx86_64.exe"
    argument_pickle_dict            : "igg_args.pkl"

geom:
    ptcloud_profile                 : "PointCloudBladeGeometry.txt"              #Name of the pointcloud-file
    ptcloud_profile_unit            : "mm"                                   #m vs mm
    beta_meta_01                    : 140                                   #Inflow angle [deg]
    beta_meta_02                    : 93                                   #Outflow angle [deg]
    x_inlet                         : -0.14                                  #Shift Inlet along x [m]
    x_outlet                        : 0.32                                  #Shift Outlet along x [m]
    pitch                           : 0.1524                               #Pitch [m]

mesh:
    factor                          : 0.9                                   #Mesh-density factor
    ogrid_factor                    : 1                                   #o-grid-node-ratio
    delta_i                         : 0.0015                                #node-distribution along fixed edges
    first_cell_width                : 0.000015                              #first cell height when factor=1
    exp_ratio                       : 1.01                                  #expansion ratio along boundary layer
    layers                          : 2                                     #fixed cells in boundary layer
    extrudeNodes                    : 6                                    #nodes along span (extrudeLength) when factor=1
    extrudeLength                   : 0.006                                  #length of extruded span
    blockStartFromChord             : 0.015                                 #LE and TE-Block Meshing
    hk_ps_shift                     : 1                                #LE and TE-Block Meshing
    hk_ss_shift                     : 1
    vk_ps_shift                     : 1.3                                #LE and TE-Block Meshing
    vk_ss_shift                     : 1
    cellwidthcoeff                  : 0.0005                                #cell width-coeff at LT and TE (stagnation-point-flow)
    streamline_nodedensity_factor   : 1                                   #define node-density factor (in/outlet vs periodic)
    yPerLowHGridBlockPitchStart     : 0.3                                   #move low-y-per-block along y-pitch
    yPerHighHGridBlockPitchStart    : 0.75                                  #move high-y-per-block along y-pitch
    shift_vk_block_xaxiscoeff       : 0.26                                  #move periodic vertices (yPer from LE) along x
    shift_hk_block_xaxiscoeff       : 0.15                                  #move periodic vertices (yPer from TE) along x
    smoothing                       : 5000                                  #smoothing iterations
