case:
    domain : "00_Ressources/02_UsedMesh/09_OpenFOAM_compCascade_0.vtk"
    blade : "00_Ressources/02_UsedMesh/BLADE_0.vtk"
    alpha : 0.01
    create :
        profile_probes: True
        streamline_probes: True
        inletoutletvelocity_probing: True
        inletoutletfieldave_probing : True
        xsclicing_probes: True
        midspanslice_probing : True
        inletoutlet_probing : True

profile_probes:
    pden_ps : 20
    pden_ss : 20
    interval_time_steps_probes : 1
    output_path : "02_Preprocessing/system"
    tolerance : 1e-6

streamline_probes:
    nop_streamline : 20
    save_dir : "02_Preprocessing/system"
    interval_time_steps_probes : 1
    beta_01 : 137
    beta_02 : 111
    teilung : 0.0765

inletoutlet_probes:
    mesh : domain
    interval_time_steps_probes: 1
    output_path : "02_Preprocessing/system"

xsclicing_probes:
    mesh : domain
    nop: 10
    interval_time_steps_probes: 1
    x_slice_one : -0.08
    x_slice_two : 0.18
    output_path: "02_Preprocessing/system"

